include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Prefer relative imports
    prefer_relative_imports: true
    
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Prefer final fields
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Prefer single quotes
    prefer_single_quotes: true
    
    # Avoid unnecessary containers
    avoid_unnecessary_containers: true
    
    # Prefer sized box over container
    sized_box_for_whitespace: true
    
    # Prefer if null operators
    prefer_if_null_operators: true
    
    # Prefer null aware operators
    prefer_null_aware_operators: true
    
    # Avoid print statements
    avoid_print: true
    
    # Prefer async/await
    prefer_async_await: true
    
    # Prefer foreach
    prefer_foreach: true
    
    # Prefer contains
    prefer_contains: true
    
    # Prefer starts_with
    prefer_starts_with: true
    
    # Prefer ends_with
    prefer_ends_with: true
    
    # Prefer is_empty
    prefer_is_empty: true
    
    # Prefer is_not_empty
    prefer_is_not_empty: true
    
    # Prefer iterable methods
    prefer_iterable_where: true
    prefer_iterable_whereType: true
    prefer_iterable_any: true
    prefer_iterable_every: true
    prefer_iterable_fold: true
    prefer_iterable_reduce: true
    prefer_iterable_toList: true
    prefer_iterable_toSet: true
    prefer_iterable_join: true
    prefer_iterable_map: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart" 